<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Genus;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * GenusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenusRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Genus[]
     */
    public function findAllPublishedOrderedBySize() : array
    {
        $query = $this->createQueryBuilder('genus');
        $query->andWhere('genus.isPublished = :published');
        $query->setParameter('published', true);
        $query->addOrderBy('genus.speciesCount', 'DESC');
        return $query->getQuery()->execute();
    }
}
