<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Genus;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\EntityRepository;

/**
 * GenusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenusRepository extends EntityRepository
{
    /**
     * @return Genus[]
     */
    public function findAllPublishedOrderedBySize() : array
    {
        $query = $this->createQueryBuilder('genus');
        $query->andWhere('genus.isPublished = :published');
        $query->setParameter('published', true);
        $query->addOrderBy('genus.speciesCount', 'DESC');
        return $query->getQuery()->execute();
    }

    /**
     * @return Genus[]|array
    **/
    public function findAllOrderedByRecentNote() : array
    {
        return $this->createQueryBuilder('genus')
            ->andWhere('genus.isPublished = :published')
            ->setParameter('published', true)
            ->join('genus.notes','genusNote')
            ->orderBy('genusNote.createdAt','DESC')
            ->join('genus.genusScientists', 'genus_scientists')
            ->addSelect('genus_scientists')
            ->getQuery()->execute();
    }
}
