<?php

namespace AppBundle\Repository;

/**
 * GenusNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenusNoteRepository extends \Doctrine\ORM\EntityRepository
{
}
