<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Genus;
use AppBundle\Entity\GenusNote;
use Doctrine\ORM\EntityRepository;

/**
 * GenusNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenusNoteRepository extends EntityRepository
{
    /**
     * @param Genus $genus
     * @return GenusNote[]
     */
    public function findAllRecentNotesForGenus(Genus $genus) : array
    {
        $query = $this->createQueryBuilder('genusNote');
        $query->andWhere("genusNote.genus = :genus");
        $query->setParameter('genus', $genus);
        $query->andWhere('genusNote.createdAt > :date');
        $query->setParameter('date', new \DateTime('-3 months'));
        return $query->getQuery()->execute();
    }
}
